"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Hashable, Sequence
from typing import Any, NamedTuple
from langchain_core.runnables import Runnable, RunnableConfig
from langgraph._internal._runnable import RunnableCallable
from langgraph.pregel._write import ChannelWriteEntry
from langgraph.types import Send

_Writer = Callable[
    [Sequence[str | Send], bool],
    Sequence[ChannelWriteEntry | Send],
]

class BranchSpec(NamedTuple):
    path: Runnable[Any, Hashable | list[Hashable]]
    ends: dict[Hashable, str] | None
    input_schema: type[Any] | None = ...
    @classmethod
    def from_path(
        cls,
        path: Runnable[Any, Hashable | list[Hashable]],
        path_map: dict[Hashable, str] | list[str] | None,
        infer_schema: bool = ...,
    ) -> BranchSpec: ...
    def run(
        self, writer: _Writer, reader: Callable[[RunnableConfig], Any] | None = ...
    ) -> RunnableCallable: ...
