"""
This type stub file was generated by pyright.
"""

from typing import Any, overload
from pydantic import BaseModel
from pydantic.fields import FieldInfo

@overload
def get_fields(model: type[BaseModel]) -> dict[str, FieldInfo]: ...
@overload
def get_fields(model: BaseModel) -> dict[str, FieldInfo]: ...
def get_fields(model: type[BaseModel] | BaseModel) -> dict[str, FieldInfo]:
    """Get the field names of a Pydantic model."""
    ...

_SchemaConfig = ...
NO_DEFAULT = ...
_RESERVED_NAMES = ...

def create_model(
    model_name: str,
    *,
    field_definitions: dict[str, Any] | None = ...,
    root: Any | None = ...,
) -> type[BaseModel]:
    """Create a pydantic model with the given field definitions.

    Attention:
        Please do not use outside of langchain packages. This API
        is subject to change at any time.

    Args:
        model_name: The name of the model.
        module_name: The name of the module where the model is defined.
            This is used by Pydantic to resolve any forward references.
        field_definitions: The field definitions for the model.
        root: Type for a root model (RootModel)

    Returns:
        Type[BaseModel]: The created model.
    """
    ...

def is_supported_by_pydantic(type_: Any) -> bool:
    """Check if a given "complex" type is supported by pydantic.

    This will return False for primitive types like int, str, etc.

    The check is meant for container types like dataclasses, TypedDicts, etc.
    """
    ...
