"""
This type stub file was generated by pyright.
"""

import asyncio
import enum
from collections.abc import (
    AsyncIterator,
    Awaitable,
    Callable,
    Coroutine,
    Generator,
    Iterator,
    Sequence,
)
from contextlib import contextmanager
from contextvars import Context
from typing import Any, Protocol, TypeGuard
from langchain_core.runnables.base import (
    Runnable,
    RunnableConfig,
    RunnableLike as LCRunnableLike,
)
from langchain_core.runnables.utils import Input, Output
from langgraph.store.base import BaseStore
from langgraph.types import StreamWriter

@contextmanager
def set_config_context(
    config: RunnableConfig, run: Any = ...
) -> Generator[Context, None, None]:
    """Set the child Runnable config + tracing context.

    Args:
        config: The config to set.
    """
    ...

def create_task_in_config_context(
    coro_factory: Callable[[], Coroutine[Any, Any, Any]], config: RunnableConfig
) -> asyncio.Task[Any]:
    """Create an asyncio.Task that inherits `config` as the child runnable context.

    `asyncio.create_task` snapshots the current contextvars onto the new task,
    so calling `create_task` while the config context is set ensures the task
    sees `config` via `var_child_runnable_config` and any tracing parent.
    """
    ...

class StrEnum(str, enum.Enum):
    """A string enum."""

    ...

ANY_TYPE = ...
ASYNCIO_ACCEPTS_CONTEXT = ...
KWARGS_CONFIG_KEYS: tuple[tuple[str, tuple[Any, ...], str, Any], ...] = ...
VALID_KINDS = ...

class _RunnableWithWriter(Protocol[Input, Output]):
    def __call__(self, state: Input, *, writer: StreamWriter) -> Output: ...

class _RunnableWithStore(Protocol[Input, Output]):
    def __call__(self, state: Input, *, store: BaseStore) -> Output: ...

class _RunnableWithWriterStore(Protocol[Input, Output]):
    def __call__(
        self, state: Input, *, writer: StreamWriter, store: BaseStore
    ) -> Output: ...

class _RunnableWithConfigWriter(Protocol[Input, Output]):
    def __call__(
        self, state: Input, *, config: RunnableConfig, writer: StreamWriter
    ) -> Output: ...

class _RunnableWithConfigStore(Protocol[Input, Output]):
    def __call__(
        self, state: Input, *, config: RunnableConfig, store: BaseStore
    ) -> Output: ...

class _RunnableWithConfigWriterStore(Protocol[Input, Output]):
    def __call__(
        self,
        state: Input,
        *,
        config: RunnableConfig,
        writer: StreamWriter,
        store: BaseStore,
    ) -> Output: ...

RunnableLike = (
    LCRunnableLike
    | _RunnableWithWriter[Input, Output]
    | _RunnableWithStore[Input, Output]
    | _RunnableWithWriterStore[Input, Output]
    | _RunnableWithConfigWriter[Input, Output]
    | _RunnableWithConfigStore[Input, Output]
    | _RunnableWithConfigWriterStore[Input, Output]
)

class RunnableCallable(Runnable):
    """A much simpler version of RunnableLambda that requires sync and async functions."""
    def __init__(
        self,
        func: Callable[..., Any | Runnable] | None,
        afunc: Callable[..., Awaitable[Any | Runnable]] | None = ...,
        *,
        name: str | None = ...,
        tags: Sequence[str] | None = ...,
        trace: bool = ...,
        recurse: bool = ...,
        explode_args: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def invoke(
        self, input: Any, config: RunnableConfig | None = ..., **kwargs: Any
    ) -> Any: ...
    async def ainvoke(
        self, input: Any, config: RunnableConfig | None = ..., **kwargs: Any
    ) -> Any: ...

def is_async_callable(func: Any) -> TypeGuard[Callable[..., Awaitable]]:
    """Check if a function is async."""
    ...

def is_async_generator(func: Any) -> TypeGuard[Callable[..., AsyncIterator]]:
    """Check if a function is an async generator."""
    ...

def coerce_to_runnable(
    thing: RunnableLike, *, name: str | None, trace: bool
) -> Runnable:
    """Coerce a runnable-like object into a Runnable.

    Args:
        thing: A runnable-like object.

    Returns:
        A Runnable.
    """
    ...

class RunnableSeq(Runnable):
    """Sequence of `Runnable`, where the output of each is the input of the next.

    `RunnableSeq` is a simpler version of `RunnableSequence` that is internal to
    LangGraph.
    """
    def __init__(
        self,
        *steps: RunnableLike,
        name: str | None = ...,
        trace_inputs: Callable[[Any], Any] | None = ...,
    ) -> None:
        """Create a new RunnableSeq.

        Args:
            steps: The steps to include in the sequence.
            name: The name of the `Runnable`.

        Raises:
            ValueError: If the sequence has less than 2 steps.
        """
        ...

    def __or__(self, other: Any) -> Runnable: ...
    def __ror__(self, other: Any) -> Runnable: ...
    def invoke(
        self, input: Input, config: RunnableConfig | None = ..., **kwargs: Any
    ) -> Any: ...
    async def ainvoke(
        self, input: Input, config: RunnableConfig | None = ..., **kwargs: Any | None
    ) -> Any: ...
    def stream(
        self, input: Input, config: RunnableConfig | None = ..., **kwargs: Any | None
    ) -> Iterator[Any]: ...
    async def astream(
        self, input: Input, config: RunnableConfig | None = ..., **kwargs: Any | None
    ) -> AsyncIterator[Any]: ...
