"""
This type stub file was generated by pyright.
"""

from datetime import timedelta
from typing import Literal
from langgraph.types import TimeoutPolicy

_SYNC_TIMEOUT_PREFIX = ...

def coerce_timeout_policy(
    value: float | timedelta | TimeoutPolicy | None,
) -> TimeoutPolicy | None:
    """Normalize a timeout value to positive-second policy fields."""
    ...

def sync_timeout_unsupported(
    name: str, *, kind: Literal["Node", "Task"] = ...
) -> ValueError:
    """Build the canonical error for using `timeout` with a sync target."""
    ...
