"""
This type stub file was generated by pyright.
"""

from typing import Any

__all__ = (
    "TAG_NOSTREAM",
    "TAG_HIDDEN",
    "START",
    "END",
    "CONF",
    "TASKS",
    "CONFIG_KEY_CHECKPOINTER",
)
TAG_NOSTREAM = ...
TAG_HIDDEN = ...
END = ...
START = ...

def __getattr__(name: str) -> Any: ...
