"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Callable, Iterator
from typing import Any, TypeVar
from uuid import UUID
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.messages import BaseMessage
from langchain_core.outputs import ChatGenerationChunk, LLMResult
from langgraph.pregel.protocol import StreamChunk
from langchain_core.tracers._streaming import (
    _StreamingCallbackHandler,
    _V2StreamingCallbackHandler,
)

T = TypeVar("T")
Meta = tuple[tuple[str, ...], dict[str, Any]]

class StreamMessagesHandler(BaseCallbackHandler, _StreamingCallbackHandler):
    """A callback handler that implements stream_mode=messages.

    Collects messages from:
    (1) chat model stream events; and
    (2) node outputs.
    """

    run_inline = ...
    def __init__(
        self,
        stream: Callable[[StreamChunk], None],
        subgraphs: bool,
        *,
        parent_ns: tuple[str, ...] | None = ...,
    ) -> None:
        """Configure the handler to stream messages from LLMs and nodes.

        Args:
            stream: A callable that takes a StreamChunk and emits it.
            subgraphs: Whether to emit messages from subgraphs.
            parent_ns: The namespace where the handler was created.
                We keep track of this namespace to allow calls to subgraphs that
                were explicitly requested as a stream with `messages` mode
                configured.

        Example:
            parent_ns is used to handle scenarios where the subgraph is explicitly
            streamed with `stream_mode="messages"`.

            ```python
            def parent_graph_node():
                # This node is in the parent graph.
                async for event in some_subgraph(..., stream_mode="messages"):
                    do something with event # <-- these events will be emitted
                return ...

            parent_graph.invoke(subgraphs=False)
            ```
        """
        ...

    def tap_output_aiter(
        self, run_id: UUID, output: AsyncIterator[T]
    ) -> AsyncIterator[T]: ...
    def tap_output_iter(self, run_id: UUID, output: Iterator[T]) -> Iterator[T]: ...
    def on_chat_model_start(
        self,
        serialized: dict[str, Any],
        messages: list[list[BaseMessage]],
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        tags: list[str] | None = ...,
        metadata: dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_llm_new_token(
        self,
        token: str,
        *,
        chunk: ChatGenerationChunk | None = ...,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        tags: list[str] | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_llm_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_chain_start(
        self,
        serialized: dict[str, Any],
        inputs: dict[str, Any],
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        tags: list[str] | None = ...,
        metadata: dict[str, Any] | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_chain_end(
        self,
        response: Any,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_chain_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...

class StreamMessagesHandlerV2(StreamMessagesHandler, _V2StreamingCallbackHandler):
    """v2 variant of `StreamMessagesHandler`.

    Declaring `_V2StreamingCallbackHandler` as a base flips
    `BaseChatModel.invoke` to route through `_stream_chat_model_events`
    (firing `on_stream_event`) instead of `_stream` (firing
    `on_llm_new_token`). Inherits `on_stream_event` from the parent,
    which forwards protocol events onto the messages stream channel.

    Pregel attaches this class instead of the v1 handler only when
    `StreamingHandler` opts in via the internal
    `CONFIG_KEY_STREAM_MESSAGES_V2` config key; direct
    `graph.stream(stream_mode="messages")` callers keep the v1
    AIMessageChunk shape.
    """
    def on_llm_new_token(
        self,
        token: str,
        *,
        chunk: ChatGenerationChunk | None = ...,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        tags: list[str] | None = ...,
        **kwargs: Any,
    ) -> Any:
        """Intentional no-op — v1 chunks are not used on v2-flagged runs.

        The v2 marker already steers `invoke` to the event generator, so
        `on_llm_new_token` should not fire under normal routing. This
        override stays a pass-through (no call to `super()`) to make
        the intent explicit and to guard against any caller (e.g. a
        node that calls `model.stream()` directly, which still fires
        the v1 callback) leaking AIMessageChunks onto a v2-flagged
        messages stream.
        """
        ...

    def __init__(
        self,
        stream: Callable[[StreamChunk], None],
        subgraphs: bool,
        *,
        parent_ns: tuple[str, ...] | None = ...,
    ) -> None: ...
    def on_llm_end(
        self,
        response: LLMResult,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_llm_error(
        self,
        error: BaseException,
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        **kwargs: Any,
    ) -> Any: ...
    def on_stream_event(
        self,
        event: dict[str, Any],
        *,
        run_id: UUID,
        parent_run_id: UUID | None = ...,
        tags: list[str] | None = ...,
        **kwargs: Any,
    ) -> Any:
        """Forward a protocol event from `stream_events(version="v3")` as a messages stream part.

        Fires once per `MessagesData` event (`message-start`, per-block
        `content-block-*`, `message-finish`). The transformer layer
        correlates events back to a single `ChatModelStream` via
        `metadata["run_id"]` — attached here so the v1
        `stream_mode="messages"` output (which emits
        `(AIMessageChunk, metadata)` via `on_llm_new_token`) keeps its
        original metadata shape.

        Lives on the v2 handler rather than the v1 base: content-block
        events are a v2-only concept, and forwarding them only when the
        v2 handler is attached keeps the message channel's shape
        predictable for v1 callers.
        """
        ...

_MESSAGE_ROLES: frozenset[str] = ...
_MESSAGE_TYPES: frozenset[str] = ...

def ensure_message_ids(value: Any) -> None:
    """Coerce message-like write values to typed BaseMessages with stable IDs.

    Called in put_writes() before DeltaChannel writes are submitted to the
    checkpointer. Without this the checkpoint may store raw dicts or id=None
    BaseMessages; every get_state() replay then produces a different UUID and
    the same message appears with a different ID in each LangSmith trace.

    Handles three input shapes:
    - BaseMessage objects: assign a UUID if id is None.
    - Dicts with a known "role" (OpenAI-style) or "type" (LangChain format) at
      the root level: stamp "id" into the dict in-place. The reducer's
      convert_to_messages call will forward the id to the resulting BaseMessage.
    - Lists of the above: apply the same logic to each element, replacing dict
      items with coerced BaseMessages so the shared list reference seen by
      checkpoint_pending_writes and the background thread both get typed messages.

    Mutating synchronously here (before the background thread is submitted) is
    safe: the serialised bytes always reflect the post-coercion state.
    """
    ...
